# Generated by Django 5.2 on 2025-04-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color_code',
            field=models.CharField(editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(choices=[('FF0000', 'Red'), ('0000FF', 'Blue'), ('008000', 'Green'), ('FFFF00', 'Yellow'), ('FFA500', 'Orange'), ('800080', 'Purple'), ('FFC0CB', 'Pink'), ('A52A2A', 'Brown'), ('000000', 'Black'), ('FFFFFF', 'White')], help_text='Select a color', max_length=50),
        ),
    ]
