# Generated by Django 5.2.1 on 2025-06-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
