# Generated by Django 5.2.1 on 2025-06-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
