# Generated by Django 5.2.1 on 2025-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.TextField(blank=True, help_text='Comma-separated list of available sizes (e.g., S,M,L,XL)'),
        ),
    ]
