# Generated by Django 5.2.1 on 2025-06-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='imgur_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='imgur_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
