# Generated by Django 5.2.1 on 2025-06-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_imgur_url_productcolor_imgur_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='imgur_url',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='imgur_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='imgur_url',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
