# Generated by Django 5.0.1 on 2025-07-13 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'القسم', 'verbose_name_plural': 'الاقسام'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'الايميل', 'verbose_name_plural': 'الايميلات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'اللون', 'verbose_name_plural': 'الالوان'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'التقيم', 'verbose_name_plural': 'التقيمات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='القسم'),
        ),
    ]
